---
name: Tests

on:
  pull_request:

jobs:

  emulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        env:
          NETWORK: emulator
          RPC_ADDRESS: localhost:3569
          NON_FUNGIBLE_TOKEN_ADDRESS: f8d6e0586b0a20c7
          EXAMPLE_NFT_ADDRESS: 01cf0e2f2f715450
          PDS_ADDRESS: f3fcd2c1a78f5eee
          FLOW_PDS_ADMIN_ADDRESS: f3fcd2c1a78f5eee
          FLOW_PDS_ADMIN_PRIVATE_KEY: 9c687961e7a1abe1e445830e7ec118ffd1e2a0449cf705f5476b3f100e94dc29
          FLOW_PDS_ACCESS_API_HOST: localhost:3569
          TESTNET_OWNER: ${{ secrets.TESTNET_OWNER}}
          TESTNET_ISSUER: ${{ secrets.TESTNET_ISSUER}}
          TESTNET_PDS: ${{ secrets.TESTNET_PDS}}
        run: ./tests-with-emulator.sh
